Portfolio: finish mobile version
SSEKPIUS/Portfolio pull request #2
Opened 2022-09-23 15:02 UTC by SSEKPIUS

2022-09-23 16:10 UTC, Ugboaja-Uchechi requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 

## Required Changes ♻️

- [ ] Kindly create a descriptive pull request talking about what you did for this mile-stone 🙏 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 16:10 UTC, Ugboaja-Uchechi commented on index.html
> +                </div>
- [ ] Kindly group the list of `programming languages` in a `ul` tag and each of them in an `li` tag. This would make your code more semantic 🙏

2022-09-23 16:10 UTC, Ugboaja-Uchechi commented on index.html
> +                </div>
- [ ] Kindly use a `button` or an `a` tag to create all your `buttons` 🙏 . This is best practice and would make your code more semantic.

2022-09-23 16:10 UTC, Ugboaja-Uchechi commented on index.html
> +              <span class="primary-text">About me</span>
- [ ] Kindly use between a `h2` to `h6` tag as this a heading. This would help indicate for screen-readers the beginning of a new `section` 🙏

2022-09-23 16:10 UTC, Ugboaja-Uchechi commented on index.html
> +              <span class="description">Hello I’m a software developer! I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and h
- [ ] Kindly use a `p` tag as this is a `paragraph text` . 🙏

2022-09-26 08:35 UTC, Olamarx approved these changes
Hi @SSEKPIUS, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/14tLmsD1i0iALu/giphy.gif"/>

## Highlights
- Linter Passes ✔️ 
- Project works as expected ✔️ 
- Good use of Git and Github flow ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 10:04 UTC, merged